apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-input
  labels:
    app: logstash
data:
  input.conf: |
    input {
      beats {
         port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "tomcat-logs"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipelines
  labels:
    app: logstash
data:
  pipelines.yml: |
    - pipeline.id: filebeat_petclinic
      path.config: /usr/share/logstash/config/input.conf
      queue.type: "memory"

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.0.0
        ports:
        - containerPort: 5044
        volumeMounts:
        - name: logstash-input
          mountPath: /usr/share/logstash/config/input.conf
          subPath: input.conf
        - name: logstash-pipelines
          mountPath: /usr/share/logstash/config/pipelines.yml
          subPath: pipelines.yml
      volumes:
      - name: logstash-input
        configMap:
          name: logstash-input
      - name: logstash-pipelines
        configMap:
          name: logstash-pipelines
---
kind: Service
apiVersion: v1
metadata:
  name:  logstash
spec:
  selector:
    app:  logstash
  type: NodePort
  ports:
  - name:  "logstash-api"
    port:  5044
    targetPort:  5044